[package]
name = "intranet-epoch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
intranet-crypto.workspace = true
intranet-governance.workspace = true
intranet-identity.workspace = true
intranet-storage.workspace = true

openmls.workspace = true
openmls_basic_credential.workspace = true
openmls_rust_crypto.workspace = true
openmls_traits.workspace = true
chacha20poly1305.workspace = true
thiserror.workspace = true

[lints]
workspace = true
