[package]
name = "intranet-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
intranet-crypto.workspace = true
intranet-governance.workspace = true
intranet-identity.workspace = true
intranet-invite.workspace = true
intranet-ledger.workspace = true
intranet-storage.workspace = true

async-trait.workspace = true
futures.workspace = true
libp2p.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true

[dev-dependencies]
intranet-search.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }

[lints]
workspace = true
