[package]
name = "intranet-identity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
intranet-crypto.workspace = true

bip39.workspace = true
libp2p-identity.workspace = true
slip10_ed25519.workspace = true
thiserror.workspace = true

[lints]
workspace = true
